### ISSUE TITLE
Problem with reverse Proxy Settings

### ISSUE THREAD

**Issue by TobiasDax** [getferdi/server-docker#2]
Is there a way to use ferdi-docker with a subfolder domain? 
like `https://YOUR-DOMAIN/ferdi` 

everything i tried so far always redirects out of the subfolder to the domain itself creates problems with other paths.

**Comment by xthursdayx** [comment]
Sorry, I missed this notification somehow. I'm not entirely sure, since I run everything as a subdomain. Should be possible, so I'll look into it and see if I can find a working NGINX subfolder conf.

**Comment by xthursdayx** [comment]
@TobiasDax  Can you try adding this to your default NGINX server block:

```
location /ferdi {

    include /config/nginx/proxy.conf;
    rewrite /ferdi(.*) $1 break;
    proxy_pass http://<server_ip>:3333;
    proxy_set_header        X-Real-IP            $remote_addr;
    proxy_set_header        X-Forwarded-For	     $proxy_add_x_forwarded_for;
    proxy_set_header        Host                 $host;
    proxy_set_header        X-Forwarded-Proto    https;
}
```
