### ISSUE TITLE
How do updates work?

### ISSUE THREAD

**Issue by vantezzen** [getferdi/server-docker#3]
@xthursdayx I recently pushed a fix to the server repository - how do those changes get transferred into the docker image? What do we have to do to update the docker image?

**Comment by xthursdayx** [comment]
I'm not entirely sure to tell you the truth. I just manually triggered a rebuild of the image but it didn't trigger my local container to see that as an update. I'll look into it.

**Comment by xthursdayx** [comment]
After consulting with the folks who coded the base image that this image is built it seems that triggering a new build should prompt people's containers to see an update. So I'll go ahead and close this for now and we can reopen it if the updates don't seem to be working.
