### ISSUE TITLE
Password reset email not sending

### ISSUE THREAD

**Issue by xthursdayx** [getferdi/server-docker#6]
I just found out that the email password reset option is not working when ferdi-server is running in this docker container. What does ferdi-server use to send email? Postfix or Sendmail?

**Comment by vantezzen** [comment]
Emails need to be configured in the `.env` file: 

https://github.com/getferdi/server/blob/ab43c12c8416177a5e0c4f4a9bb18e122d02f76d/.env.example#L26-L31

**Comment by xthursdayx** [comment]
Great, thanks. I'll work on integrating this into the docker container.

**Comment by xthursdayx** [comment]
In my testing version of this container I updated the config scripts and env variables to add the smtp sendmail settings however I'm finding that it is just printing the password reset email in the docker log rather than actually sending it. I ran the docking using the environmental variable for Google's smtp server: `-e MAIL_CONNECTION=smtp` `-e SMPT_HOST=smtp.gmail.com` and `-e SMTP_PORT=465` with a google username, password, and mailsender. I assume that this is working in the non-dockerized version? You shouldn't have to map any outbound port for smtp to function, since it is connecting to another smtp server elsewhere, but something seems to be stopping the program from properly connecting to the smtp server and sending mail. 

You can see the changes I've made so far (and which I will add to this image once they're working) [here in the readme](https://github.com/xthursdayx/ferdi-server-docker) and here in the [.env.example](https://github.com/xthursdayx/ferdi-server-docker/blob/master/root/defaults/.env.example).

Any ideas?

**Comment by vantezzen** [comment]
Our Ferdi server uses mailgun and not SMTP to send mails so I don't really have any experience with setting it up with SMTP. Have you set the `MAIL_SENDER`, too? Also, you have a typo in `SMPT_HOST`.

**Comment by xthursdayx** [comment]
Yeah, `MAIL_SENDER` is set as the google account, and the typo was just from me typing here, it's correct in my repo and in the commands I used to try running my modified version of the docker. I can look into mailgun as well, I just thought that more people would likely be familiar with/already using SMTP, so that would be the best option for the most number of users. I'll keep looking into it.

**Comment by xthursdayx** [comment]
After reading through the nodemailer SMTP documentation it looks like there may be a couple of extra variables needed to get SMTP sending to work, including documentation regarding use SSL via port 465. I will update the docker container accordingly, but first the base ferdi server needs to integrate these changes, so I've opened this PR: https://github.com/getferdi/server/pull/31

After the PR is merged I will update my testing container and if all works as expected update the production docker container.

**Comment by xthursdayx** [comment]
This is now fixed after the previously mentioned PR was merged and my recent commit https://github.com/getferdi/server-docker/commit/ac9cb8690fd762c39d1188be9edba207ab1760e7. Closing this now.
