### ISSUE TITLE
DB_SSL and MAIL_SSL are not reflected in latest image

### ISSUE THREAD

**Issue by ikaruswill** [getferdi/server-docker#7]
Changes made in https://github.com/getferdi/server/pull/33 are not reflected in the latest docker image.

Currently, SSL variable still exists, and is still not yet split into MAIL_SSL and DB_SSL.

Though it seems like it has no impact on running the app, I feel the documentation can be improved on how to better configure this Docker image.

**Comment by xthursdayx** [comment]
Thanks for pointing this out, the readme and other files have now be updated.
